language: clojure
lein: lein2
before_script:
- lein2 version
script: lein2 test
after_success:
- lein2 pallet-release push
env:
  global:
    secure: RRqx7kSwNiGOaaebJLxdiRboVU0yfh0DmAEneAyHgbfEFCKy67tH1ilXvtcHHSEEoTSE/wKrUOjCi/kKjDSR9yneMMiLAOWloBx3INZ/K4Z66/T2AAZdFbbIEuroAF7YokIICE7XR07RAFPGCYS/xHACf0Wac1W3+PS4zU1RL9M8TnBJyivG7tohQUAd2KTyhh2RwLI5/k/WDae/YcjiDg7eTek+gbxMAyrakimPCQaCLPN1E3RkjmHiBZWS9Vqjs2QtKjzVT4ZnDyJbUaMbSJhobjF3I7BHFcg3h3IMq9CpgrWt0wL/I9FZKHfIaDHVHGOX8sE9tckandhdNTcI6wjMZAfp/NCuSzJuZiaRGygEZ69gcWMUNC+gu9WLkitmxYnqzDLiKLyNnjsiL/436+/86rtRv8OEzGXaTKWsf/K/1aCOE9YUnTwzWpLvbeCsEobUf9dz5FsjbZvmxwYshwYm21xY0PPmKLbVkyK7cvlZPUU57BSdlCK6/fVqrxJqGYJJIiX59fXJ0Ha62Scg+AzOaht7pEUtrvlJIqeKxwNCJFApzWNZ3oFYzJlC7bQnGYsSsUIryQ2h44rVSdzs2YvPLCH6fExMBWpfXwvS67b/UrI2inRs9gVdD2NJqQtjj3Jj6Z3nd+h1hQGTgBHd/pNnylR2GFAXf+szFokn0vQ=
